### ISSUE TITLE
[Feature Request] Add support for piping image content to jp2a

### ISSUE THREAD

**Issue by SunPodder** [cslarsen/jp2a#19]
I was thinking to play a video on the terminal. I will get each frame of a video as a image and then pass it to jp2a. So first I tried to pipe a image content to it with `cat image.jpg | jp2a` but it doesn't work. So can you please add this functionality please?

**Comment by Talinx** [comment]
You  can add `-` to read an image from stdin, e.g.: `cat image.jpg | jp2a -`.
