### ISSUE TITLE
Not working on WSL Ubuntu Distro

### ISSUE THREAD

**Issue by Krauzer94** [cslarsen/jp2a#20]
`Objective`: I'm trying to make it work on Ubuntu WSL via Windows.

### Error message
Error message while trying to install it:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package jp2a
```

### What I tried
Did a fresh install of WSL with Ubuntu and tried running jp2a.

Installing using the command:
```
sudo apt-get install jp2a
```

Also did the following commands:
```
sudo apt-get update
sudo apt-get upgrade
```

Any clues?

**Comment by Talinx** [comment]
Have you tried running
```bash
sudo apt-get update
sudo apt-get install jp2a
```
in this order?
`sudo apt-get install jp2a` failed for me with the same message on a fresh install, but it worked after `sudo apt-get update`.

If this still doesn't work, what is the output of `apt search jp2a`?

**Comment by Krauzer94** [comment]
### sudo apt-get update
This is the result:

```
krauzer@computer:~$ sudo apt-get update
[sudo] password for krauzer:
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Err:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Ign:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Err:1 http://archive.ubuntu.com/ubuntu jammy InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

`Note`: Yes I ran both commands at the order you mentioned, still the same result.

### sudo apt-get install jp2a
This is the result of `apt search jp2a`:
```
krauzer@computer:~$ apt search jp2a
Sorting... Done
Full Text Search... Done
krauzer@computer:~$  _
```

**Comment by Talinx** [comment]
This seems to be a DNS problem. Ubuntu fails to convert 'archive.ubuntu.com' and 'security.ubuntu.com' to IP addresses. This in turn prevents Ubuntu from figuring out which packages exist in the first place.

Possible solutions:

- Wait. Maybe the DNS server you are using has some temporary problem.
- Change your DNS server in Windows or Ubuntu.

You can check which DNS server you are using with:
```bash
cat /etc/resolv.conf | grep nameserver
```
To test if DNS is actually the problem you can edit this file and change your nameserver to e.g. 8.8.8.8 with the following line in `/etc/resolv.conf`:
```
nameserver 8.8.8.8
```
And then run `sudo apt-get update` again.  
(You can also test DNS lookup by running e.g. `host archive.ubuntu.com` to resolve `archive.ubuntu.com` to IP addresses.)

This solution is only temporary, by default Windows automatically regenerates `/etc/resolv.conf`. (If this problem persists you can't update packages.) [This](https://askubuntu.com/a/1402581) is probably the easiest permanent solution.

**Comment by Krauzer94** [comment]
I don't use WSL or this tool anymore
